### ISSUE TITLE
Serilog.Settings.Configuration compatibility?

### ISSUE THREAD

**Issue by frg** [serilog/serilog-sinks-map#2]
Hey, 

Aare you able to use this sink with the `Serilog.Settings.Configuration` package?

I'm checking out `Serilog.Settings.Configuration` source and it seems like they only support `Action<LoggerConfiguration>` and Action`<LoggerSinkConfiguration>`.

https://github.com/serilog/serilog-settings-configuration/blob/fae623c627496f00fcfab29f721cd49b2bbed989/src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationSectionArgumentValue.cs#L20

Does anyone have any ideas of how we can get around this?
ie. Conform to the supported actions, ask `Serilog.Settings.Configuration `to support `Action<string, ...>` (this seems to edge case for them though)

**Comment by nblumhardt** [comment]
Hi @frg; I think it'd be a bit awkward to plug in via _appsettings_ as things stand, because of the "functional" API. As you say, it could be done, but it's probably too much of an edge case at this stage to justify the kind of investment that'd have to be made to support it, at least in the short term.

Is it just a matter of the alternative being awkward? (I.e. using code to configure the sink, and looking up any required configuration from appsettings manually?)

**Comment by nblumhardt** [comment]
I'll close this ticket now as I don't think there's a near-term way forwards (considering a few angles, such as _Serilog.Filters.Expressions_ integration...) - hopefully the right ingredients will come together to enable this sometime in the future. Thanks @frg!
