### ISSUE TITLE
Target .NET 4.5?

### ISSUE THREAD

**Issue by KorsG** [serilog/serilog-sinks-map#23]
I am working on some legacy .NET 4.5 - 4.6.2 projects that cant be upgrade because they are plugins to another system, and although I can use this package as-is, it requires a dependency to NETStandard.Library which outputs a ton of dll's we have to deploy (manually ofcourse ;-)). 

Would you be open for targeting .NET 4.5 like some of the other sinks or at least 4.6.2? I could make a pull request if you want 🙂

**Comment by nblumhardt** [comment]
Thanks for the heads-up. I think that we're likely to start start to phasing out direct .NET Framework support (and `netstandard1.x` support) across Serilog, in favor of targeting `netstandard2.0`, since actually installing/testing on those old targets is getting harder. I'd rather not add more .NET Framework support, since this will cause churn for people when we inevitably deprecate/remove it.

Right now I think, given the small size of this codebase (it's only two source files), the best option will be to copy the source and include it somewhere in your project.

**Comment by KorsG** [comment]
Thank you for the thorough explanation behind the reasoning of this, and I completely understand.

The current state of serilog is awesome and I can easily live with being "stuck" on the current versions for these legacy projects. 
My only request is that the last seq sink with .NET Framework support will continue to work with newer versions of seq for quite a while, since we will probably have to work with these legacy project for many years to come... and I guess it will be the same for many others 🙂

Anyhow, I am closing this and will probably just copy the source files as you suggested - thanks again!
